// Docs site settings for @bndynet/docs.
// Each entry in `nav` becomes one top-menu item. Items with `docsPath`
// expose an autogenerated sidebar for <mdxRoot>/<docsPath>.
/** @type {import('@bndynet/docs').DocsConfig} */
module.exports = {
  title: 'Bing\'s Website',
  name: 'Bing Zhang',
  tagline: '',
  logo: 'https://static.bndy.net/images/logo_fill.svg',
  url: 'https://bndy.net',
  baseUrl: '/',
  copyright: `Copyright © ${new Date().getFullYear()} BNDY-NET`,
  blog: true,
  mdxRoot: './docs',
  nav: [
    { label: 'Docs', docsPath: '.' },
    { label: 'Blog', href: '/blog'},
    { label: 'iChat', href: '/iframe?url=https://bndynet.github.io/ichat/'},
    { label: 'iCharts', href: '/iframe?url=https://bndynet.github.io/icharts/'},
  ],
  theme: {
    favicon: 'img/favicon.ico',
  },
};
