// Generated by IcedCoffeeScript 108.0.11
(function() {
  $(function() {
    $("input:checkbox, input:radio").iCheck({
      checkboxClass: "icheckbox_minimal",
      radioClass: "iradio_minimal",
      increaseArea: "20%"
    });
  });

}).call(this);
