name: Build+Publish

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:


permissions:
  contents: write
  id-token: write

jobs:
  publish:
    uses: bndynet/gh.flows/.github/workflows/npm.yml@main
    with:
      build-command: 'npm run build'
      deploy-folder: 'build'